# Generated by Django 3.2.6 on 2021-08-03 09:08

import src.core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=10, validators=[src.core.validators.validate_profile_names_are_only_letters])),
                ('last_name', models.CharField(blank=True, max_length=10, validators=[src.core.validators.validate_profile_names_are_only_letters])),
                ('age', models.PositiveIntegerField(default=0, validators=[src.core.validators.validate_profile_age])),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.EmailValidator, src.core.validators.validate_email_ending])),
                ('image', models.ImageField(blank=True, upload_to='profile', validators=[src.core.validators.validate_profile_image_file_size, django.core.validators.validate_image_file_extension])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
